# this yml playbook is created to create the EC2 instance.
# author--jaya chandra naveen
# date-- 22-02-2025
---
- name: Launch a free-tier EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: my-key                   # the key you just created
        instance_type: t3.micro            # free-tier eligible
        image_id: ami-0d4f84b7313c8b114    # Ubuntu 22.04 LTS in eu-north-1
        wait: true
        count: 1
        region: eu-north-1
        vpc_subnet_id: subnet-0c02031b2eda73e02
        security_group: default            # uses default SG (allow SSH by default)
        tags:
          Name: Ansible-EC2

